### ISSUE TITLE
Turrets turn back on.

### ISSUE THREAD

**Issue by BurntFood** [nomnomab/lc-turret-key#4]
Turrets will turn back on if someone puts the code for it in the terminal.

**Comment by nomnomab** [comment]
Hello!

Considering this is a client-side mod, I think this is probably fine. Mainly since using the key essentially replicates what the terminal does, but without the cool-down of it turning back on.

If someone else turns it back on themselves, I think that's okay, as well as there isn't much I can do about it unless I make the mod required on all clients.
